name: 'Generate Dilithium Signatures'
description: Generates a signatures file from a list of glob patterns
inputs:
  hexseed:
    description: Hexseed to use
    required: true
  output:
    description: Output file path
    required: false
    default: signatures.txt
  patterns:
    description: List of glob patterns to use for matching files
    required: true
runs:
  using: docker
  image: docker://ghcr.io/theQRL/actions-dilithium-sign:v1.0.0
  args:
    - ${{ inputs.hexseed }}
    - ${{ inputs.output }}
    - ${{ inputs.patterns }}
branding:
  icon: align-center
  color: green